language: php

php:
  - '7.2'
  - '7.3'
  
install:
  - composer require php-coveralls/php-coveralls:~2.1.0@stable
  - ls vendor
  - ls vendor/bin
 
before_script:
  - mkdir -p build/logs
 
script: 
  - composer update ; phpunit --bootstrap vendor/autoload.php --coverage-clover build/logs/clover.xml test

after_success:
  - ls vendor
  - ls vendor/bin
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "coveralls..."; php vendor/bin/coveralls -v; fi;'